### ISSUE TITLE
Images broken

### ISSUE THREAD

**Issue by ajmeese7** [AmruthPillai/AmruthPillai#1]
Just wanted to give you a heads up that all the language images linked on your readme are broken, if you were unaware.

![readme](https://user-images.githubusercontent.com/17814535/93105160-57ecd700-f674-11ea-8d5f-1a5825d95805.png)

Cheers!

**Comment by AmruthPillai** [comment]
😢

**Comment by ajmeese7** [comment]
Glad to see you've got it fixed. Love the new look!
